README.rdoc, app/models/shortener/shortened_url.rb, spec/models/shortened_url_spec.rb
This PR allows the unique key to be specified by the user, rather than having a randomly generated one produced. If no custom key is specified, the default behaviour occurs.
=> Allow unique key to be specified

lib/shortener/shorten_url_interceptor.rb
also preserved existing semantics of non-matching hosts (i.e.:
localhost, etc).
=> updated URL regex to match hosts with '-' characters

app/models/shortener/shortened_url.rb, spec/models/shortened_url_spec.rb
Hi. 
This patch resolves this improvement from your "future improvements" list:
"Some implementations might want duplicate links to be generated each time a user request a shortened link.".
ShortenedUrl generates unique link every time method generate is called.
=> duplicate links

app/models/shortener/shortened_url.rb
Previously, if a custom_key parameter was passed into the generate method, it would get blown away by the method generating unique keys. This adds a check when generating the unique key to only do so if there isn't already a value present.
=> Only generates a unique key if there isn't a value for unique key yet

app/models/shortener/shortened_url.rb, lib/shortener/shorten_url_interceptor.rb, shortener.gemspec, spec/models/shortened_url_spec.rb, spec/models/user_spec.rb, spec/shortener/shorten_url_interceptor_spec.rb, spec/spec_helper.rb
The main purpose is to catch URLs in the email interceptor that do not contain a subdomain.
=> RSpec failure fixes and email interceptor regex update

app/models/shortener/shortened_url.rb
This change allows monkey-patched charsets that contain regex protected characters to be used.
For example, the following initializer declares a charset that adds `-`. As a result, any short token including the `-` will currently fail token extraction.
*config/initializers/shortener.rb*
``` ruby
module Shortener
send(:remove_const, :CHARSETS) if const_defined?(:CHARSETS)
CHARSETS = {
alphanumsafe: (('b'..'z').to_a + ('b'..'Z').to_a).reject { |l| l =~ /[eiou]/i } + (0..9).to_a + %w(- _),
}
end
Shortener.default_redirect = Rails.application.secrets.web_host_share
Shortener.unique_key_length = 6
Shortener.charset = :alphanumsafe
```
=> Escape token extraction

app/models/shortener/shortened_url.rb
For routes like this, `  get '/s/:id' => 'shortener/shortened_urls#show', :as => 'shortened_url'`, it'd be nice to be use url helpers like this: `shortened_url_path(shortened_url)`. As it stands, however, the only way to generate path is like this: `shortened_url_path(shortened_url.unique_key)`.
=> Use unique_key as route param

app/helpers/shortener/shortener_helper.rb, app/models/shortener/shortened_url.rb
Don't use create_record for Rails 5.  The current code path sometimes uses create_record instead of _create_record for Rails 5, but that fix was really only meant for certain versions of Rails 4.
=> Fixes shortener in Rails 5

README.rdoc, lib/generators/shortener/templates/migration.rb, spec/dummy/db/migrate/20120213084304_create_shortened_urls_table.rb
Also, made the upgrade instructions clearer, and fixed a discrepancy between the migration template and that in the specs.
=> Fix migration template to add a category column instead of a label column

shortener.gemspec
`voight_kampff ~> 1.0.2` depends on rack 1, which makes the latest shortener cannot be included in rails 5 apps. 
```
Bundler could not find compatible versions for gem "rack":
In Gemfile:
rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.0.1, which depends on
actionpack (= 5.0.0.1) was resolved to 5.0.0.1, which depends on
-->     rack (~> 2.0)
rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.0.1, which depends on
actionpack (= 5.0.0.1) was resolved to 5.0.0.1, which depends on
rack-test (~> 0.6.3) was resolved to 0.6.3, which depends on
rack (>= 1.0)
sass-rails (~> 5.0) was resolved to 5.0.6, which depends on
sprockets (< 4.0, >= 2.8) was resolved to 3.7.0, which depends on
rack (< 3, > 1)
shortener (= 0.6.2) was resolved to 0.6.2, which depends on
voight_kampff (~> 1.0.2) was resolved …
```
=> Fix version constraint of voight_kampff

shortener.gemspec
voight_kampff `1.0` is holding rack below `2.0` which is holding me from updating to `Rails 5.0`
This update did not break any `spec` with `ruby 2.4.0`
=> Update voight_kampff to 1.1

app/controllers/shortener/shortened_urls_controller.rb
Prevents common ActionController::Base extensions from getting in the way of this being as fast an action as possible.
It’s common in apps to pollute ActionController::Base with before_filters that we don’t have any interest in.
=> Use ActionController::Metal

README.rdoc, lib/generators/shortener/templates/migration.rb
MySQL errors while adding the index because it likes a known length.
Within StackOverflow there is also a discussion regarding defacto max
url length so I set the `url` limit to the known max of 2083.
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of
-a-url-in-different-browsers
=> Add length to the url field and index

app/models/shortener/shortened_url.rb, spec/dummy/config/initializers/new_framework_default.rb
It fixes an issue with nil owners in rails 5 applications. 
The tests were validating a dummy app without the new framework default.
This pull request adds the initializer and the optional code in the belongs to association.
I found an issue: https://github.com/jpmcgrath/shortener/issues/100
=> It fixes an issue with nil owners in rails 5 applications. 

README.rdoc, lib/shortener.rb, spec/controllers/shortened_urls_controller_spec.rb
This would allow you to easily override the charset with whatever you wanted to allow, like allowing dashes for instance:
In initializers/shortener.rb you could then have something like:
```
Shortener.charset = ("a".."z").to_a + ("A".."Z").to_a + (0..9).to_a + ["-", "_"]
```
=> Allow custom charsets

app/models/shortener/shortened_url.rb, spec/models/shortened_url_spec.rb
previously fixed in #106 via handling `ActiveRecord::RecordNotUnique` with expectation to protect from race conditions, but there was more general problem than race conditions, uniqueness of token was checked by `exists?` query with wrong scope as result same token with different category was accepted as unique, relate issue #108 
so currently `ActiveRecord::RecordNotUnique` exception is handled inside transaction as result retry has no effect when PostgreSQL is used, as solution I have fixed `exists?` query which was used before #106 so it should properly check token uniqueness without raising exception, what about race conditions they will continue to be handled with rescue and DBs which allow to do it in same transaction as before
=> Fix token uniqueness, closes: #108, #106

shortener.gemspec
- The property is removed without a replacement.
=> gemspec: Drop rubyforge_project property

shortener.gemspec
The RubyGems gemspec property `rubyforge_project` has been removed without a replacement. This PR removes that property.
* [RubyForge was closed down in 2013][1].
* [rubygems/rubygems#2436 deprecated the `rubyforge_project` property][2].
[1]: https://twitter.com/evanphx/status/399552820380053505
[2]: rubygems/rubygems#2436
=> gemspec: Drop defunct property rubyforge_project

.travis.yml, spec/controllers/shortened_urls_controller_spec.rb
This does 2 things:
- It fixes the spec which I added in the rails6 upgrade to always pass
- It excludes impossible ruby / rails versions from the build matrix
=> Fixes to get CI to be green again

README.rdoc
The "future improvements" section of the Readme was written in 2011 after the initial release.
The gem is now a stable piece of many systems, and future improvements are directed by the community, not some roadmap dotpoints written almost 9 years ago..
The future is now!
=> Remove "future improvements" section from README

README.rdoc, app/models/shortener/shortened_url.rb, lib/shortener.rb, spec/models/shortened_url_spec.rb
=> Add option to disable URL normalization

README.rdoc, app/models/shortener/record.rb, app/models/shortener/shortened_url.rb
Since Rails 6.1+, the `connects_to` method can only be called on ActiveRecord::Base or abstract classes, otherwise, a NotImplementedError will be thrown.
This PR creates a hook to allow connecting to a distinct database, other than the main one.
=> Allow to configure different database for shortened_urls table

app/models/shortener/shortened_url.rb, spec/spec_helper.rb
Don't pre-format the Time passed to the `unexpired` scope. This allows the ActiveRecord adapter to format the date according to it's own needs.
Maybe addresses #144 problems, but it seems like they probably have an incorrectly configured application.
Before SQL:
```
D, [2021-11-30T22:51:27.785105 #91313] DEBUG -- :   Shortener::ShortenedUrl Exists? (0.1ms)  SELECT 1 AS one FROM "shortened_urls" WHERE ("shortened_urls"."expires_at" IS NULL OR "shortened_urls"."expires_at" > '2021-12-01 06:51:27') AND "shortened_urls"."id" = ? LIMIT ?  [["id", 279], ["LIMIT", 1]]
D, [2021-11-30T22:51:27.785193 #91313] DEBUG -- :   ↳ activerecord (6.1.4.1) lib/active_record/log_subscriber.rb:119:in `debug'
D, [2021-11-30T22:51:27.785447 #91313] DEBUG -- :   Shortener::ShortenedUrl Exists? (0.1ms)  SELECT 1 …
```
=> Let active record format the Time

README.rdoc
Hello, I just stumbled on to this while trying the library.
When  using:
```
Shortener::ShortenedUrl.generate("example.com/page", nil, expires_at: 24.hours.since)
```
There is a `Too many argument error, got 2 expecting 1`
I think we can omit the owner completely at line 166,
like so:
```
You can omit owner:
Shortener::ShortenedUrl.generate("example.com/page", expires_at: 24.hours.since)
```
=> Typo in documentation expirable URLs

lib/shortener/engine.rb, shortener.gemspec
Fixes https://github.com/jpmcgrath/shortener/issues/151
I was getting
```
NoMethodError in Shortener::ShortenedUrlsController#show
undefined method `exists?' for File:Class
```
when using this gem with ruby 3.2.1,
the error was caused voight_kampff using `File.exists?` (removed in Ruby 3) instead of `File.exist?`.
This was fixed in the 2.0 release of voight_kampff
https://github.com/biola/Voight-Kampff/commit/b24e698959c1fa1470f59a26a022461c8f35d26d
rspec tests passed
```
$ /usr/local/rvm/gems/ruby-3.2.1/bin/bundle exec rspec
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. …
```
=> Upgrade voight_kampff to 2.0 (ruby 3 compatible)
